FROM node:24-bookworm-slim AS base

# build stage
FROM base AS deps

RUN corepack enable && corepack prepare pnpm@9 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile --prod

FROM base AS builder

RUN corepack enable && corepack prepare pnpm@9 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN sed -i "s/images:/output: 'standalone',images:/" next.config.ts

RUN pnpm run build

# run stage
FROM base AS runner

ENV NODE_ENV=production
ENV HOSTNAME=

RUN echo 'deb http://deb.debian.org/debian bookworm-backports main' >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    supervisor curl jq jc borgbackup/bookworm-backports openssh-server libnss-wrapper && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Remove the SSH host keys generated by the openssh-server install so the image
# never ships shared host keys. Fresh keys are generated at first boot by the
# entrypoint.
RUN rm -f /etc/ssh/ssh_host_*

WORKDIR /app

# App files stay root:root (world-readable). Node runs as an unprivileged user
# and only needs read/execute access. Keeping the code root-owned makes it
# immutable from the running process: a compromised app cannot rewrite its
# own binaries to persist. Everything writable lives in the volumes or /tmp.
COPY --from=builder /app/docker/docker-bw-init.sh /app/LICENSE ./
COPY --from=builder /app/helpers/shells ./helpers/shells
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/docker/supervisord.conf ./
COPY --from=builder /app/docker/sshd_config /etc/ssh/sshd_config

# Fixed paths for mounted volumes
ENV DATA_DIR="/data"
ENV SSH_MOUNT_DIR="$DATA_DIR/ssh"
ENV SSH_CLIENT_DIR="$SSH_MOUNT_DIR/auth"
ENV SSH_HOST_KEYS_DIR="$SSH_MOUNT_DIR/host_keys"
ENV AUTHORIZED_KEYS_FILE="$SSH_MOUNT_DIR/authorized_keys"
ENV REPOS_DIR="$DATA_DIR/repos"

# Borg and the fake passwd entry share a writable home on the tmpfs
ENV BORG_BASE_DIR="/tmp/borgwarehouse"

# The container never runs as root: it starts directly as the UID:GID given by
# the runtime and libnss-wrapper supplies the passwd entry that ssh requires.
USER 1001:1001

EXPOSE 3000 2222

ENTRYPOINT ["./docker-bw-init.sh"]
