[supervisord]
nodaemon=true
loglevel=error
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/home/borgwarehouse/tmp/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D -e
environment=LD_PRELOAD="libnss_wrapper.so",NSS_WRAPPER_PASSWD="/tmp/passwd",NSS_WRAPPER_GROUP="/tmp/group"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
redirect_stderr=false

[program:borgwarehouse]
command=/usr/local/bin/node server.js
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
redirect_stderr=false
